version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - "5432:5432"
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
  back:
    build:
      context: ./backend
    command: bash -c "bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./backend:/backend
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
  front:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/frontend
    command: sh -c "PORT=3001 yarn run dev"
    ports:
      - 3001:3001
volumes:
  postgres_data: